### ISSUE TITLE
landings_data.rmd - didnt make it into book

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/tech-memo#30]
Sean Just added a new file (landings_data.rmd).
I dont know how to rebuild the book to add a chapter. Can you do this?
 @sgaichas

**Comment by slucey** [comment]
I'm a slacker and posted it last night.  It needs to be included in the
book.

Sean


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by sgaichas** [comment]
just added, building now
