### ISSUE TITLE
handling citations and bibliographies

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/tech-memo#5]
We will need contributors to have citations in a readable format, the easiest is bibtex (a .bib file). Most citation software can produce this, though I'm not sure about endnote. At present I put a separate bib file to go with the conceptual models indicator rmd file. Will we want everyone to have a separate bib file for each indicator? Or keep them all in one file? Bookdown can probably do either way but we should provide some guidance. I also added a line to place the bibliography where we want it in the skeleton file; this is nonstandard but doable if we add `<div id="refs"></div>` after the #References section and specify bibliography: indicator.bib as the last line of the YAML header (not indented).

**Comment by slarge** [comment]
From the [bookdown book](https://bookdown.org/yihui/bookdown/citations.html), it seems that the best bet might be have a .bib for each .rmd and to include the *.bib files in the index.rmd YAML section.

```
--- 
bibliography: ["one.bib", "another.bib", "yet-another.bib"] 
biblio-style: "apalike" 
link-citations: true 
--- 

```
Pros: keeps things compartmentalized 
Cons: it could double the number of files to keep track of...

**Comment by slarge** [comment]
@slucey @sgaichas -- I'm going to go ahead and close this since it looks like compartmentalization will work.
