### ISSUE TITLE
Draft tech memo components (due 30 July)

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/tech-memo#7]

**Comment by sgaichas** [comment]
In the order of current SOE:
- [ started ] Conceptual models
- [ draft done ] Single species status plot
- [ ] Species groupings table
- [ ] Commercial landings, by group and total
- [ ] Recreational landings
- [ ] Commercial revenue (Bennet indicator)
- [ ] Commercial revenue total and managed subset
- [ ] Commercial fleet diversity (and fleet count)
- [ ] Commercial diversity in species revenue
- [ ] Recreational opportunities (N anglers and trips)
- [ ] Mariculture
- [ ] Harmful algal blooms
- [ ] Community social vulnerability x reliance on commercial and recreational fisheries
- [ ] Climate vulnerability of selected fishing communities
- [ ] Harbor porpose bycatch trend and PBR
- [ ] Right whale population trend
- [ ] Resource species biomass trends, by group and total
- [ ] Species diversity (ichthyoplankton)
- [ ] Along shelf distribution and depth trends 
- [ ] Historical and current distributions (kernel density plots) 
- [ ] Thermal habitat projections 
- [ ] Modeled habitat trends
- [ ] Incoming species (observer data)
- [ ] Long-term ocean temperature (SST)
- [ ] Annual cycle ocean temperature
- [ ] Annual cycle primary production and Chl a
- [ ] Seasonal SST anomaly maps
- [ ] Primary production and Chl a anomaly maps
- [ ] Zooplankton abundance anomaly
- [ ] Small-Large copepod index
- [ ] Primary production ratio
- [ ] Groundfish condition
- [ ] Groundfish productivity (small fish to large fish biomass)

**Comment by seanhardison1** [comment]
Fin
